# This workflows will create a new demo repository using The Hatchlor for demonstration purposes

name: Build demo

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'Project configuration'
        required: true
        type: choice
        options:
          - default.yml
          - lock-file.yml

jobs:
  make-demo:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        path: ./hatchlor-enhanced-template

    - name: Setup Python environment
      uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: 'latest'
        environment-file: ./hatchlor-enhanced-template/.github/test_environment.yml
        init-shell: >-
          bash
          powershell
        cache-environment: true
        post-cleanup: 'all'

    - name: Setup git
      run: |
        git config --global user.email "github.action@example.com"
        git config --global user.name "Github Action"

    - name: Run cookiecutter
      run: cookiecutter --no-input ./hatchlor-enhanced-template --config-file ./hatchlor-enhanced-template/configs/${{ github.event.inputs.config }}

    - name: Debug help - list files
      working-directory: ./hatchlor-enhanced-demo
      run: |
        pwd
        ls -lR

    - name: Prepare test of hatch commands due to errors /1.
      working-directory: ./hatchlor-enhanced-demo/src/hatchlor_enhanced_demo
      run: |
        pwd
        hatch run lint:fix skeleton.py

    - name: Prepare test of hatch commands due to errors /2.
      working-directory: ./hatchlor-enhanced-demo/tests
      run: |
        pwd
        hatch run lint:fix test_skeleton.py

    - name: Prepare test of hatch commands due to errors /3.
      working-directory: ./hatchlor-enhanced-demo/docs/scripts
      run: |
        pwd
        hatch run lint:fix gen_ref_nav.py

    - name: Test some hatch commands
      working-directory: ./hatchlor-enhanced-demo
      run: |
        hatch run fibonacci 10
        hatch run test:cov
        hatch run lint:all
        # hatch run pre-commit run --all-files

    - name: Remove git repo for next step
      working-directory: ./hatchlor-enhanced-demo
      run: rm -rf .git

    - name: Push to the-hatchlor-enhanced-demo
      uses: cpina/github-action-push-to-another-repository@devel
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: "hatchlor-enhanced-demo/"
        destination-github-username: "dornech"
        destination-repository-username: "dornech"
        destination-repository-name: "the-hatchlor-enhanced-demo"
        user-email: dornech@gmx.de
        commit-message: "Initial commit"
        target-branch: main
